-- CreateTable
CREATE TABLE "CashDrawer" (
    "id" TEXT NOT NULL,
    "Open" TEXT,
    "Close" TEXT,
    "OpeningBalance" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "ClosingBalance" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "TotalSales" INTEGER NOT NULL,
    "SalesAmount" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "Cash" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "Credit" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "Card" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "DroppedCash" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "CashWithdrawn" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "Refunds" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "TotalExpenses" DOUBLE PRECISION NOT NULL DEFAULT 0.0,
    "Date" TEXT,
    "HotelId" TEXT NOT NULL,
    "Status" TEXT NOT NULL DEFAULT 'Active',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CashDrawer_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "CashDrawer_id_key" ON "CashDrawer"("id");

-- AddForeignKey
ALTER TABLE "CashDrawer" ADD CONSTRAINT "CashDrawer_HotelId_fkey" FOREIGN KEY ("HotelId") REFERENCES "Hotels"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
